server:
  port: 7002
spring:
  application:
    name: eureka-server
  profiles: peer2
eureka:
  instance:
    hostname: peer2
  client:
    service-url:
      defaultZone: http://peer1:7001/eureka/,http://peer3:7003/eureka/